# Generated by Django 3.2 on 2021-04-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Needy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email_id', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=200)),
                ('req', models.CharField(default='', max_length=200)),
                ('state', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('pub_date', models.DateField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(default='', max_length=200)),
                ('state', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('contact_name', models.CharField(default='', max_length=200)),
                ('email_id', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=200)),
                ('last_updated', models.DateField(verbose_name='last updated')),
            ],
        ),
    ]
