# Generated by Django 3.2 on 2021-04-20 23:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Res_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_name', models.CharField(max_length=50)),
                ('more_info', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, default=django.utils.timezone.now)),
                ('contact_name', models.CharField(default='', max_length=200)),
                ('email_id', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('verified', models.BooleanField(default=False)),
                ('updated_at', models.DateField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receiver.city')),
                ('resource_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='receiver.res_type', verbose_name='resc_type')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receiver.state')),
            ],
        ),
        migrations.CreateModel(
            name='Needy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=200)),
                ('email_id', models.CharField(default='', max_length=200)),
                ('phone', models.CharField(default='', max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receiver.city')),
                ('resource_name', models.ForeignKey(default='del', on_delete=django.db.models.deletion.SET_DEFAULT, to='receiver.res_type', verbose_name='resc_type')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='receiver.state')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receiver.state'),
        ),
    ]
