# Generated by Django 3.2 on 2021-04-20 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='country',
            new_name='state',
        ),
    ]
