# Generated by Django 3.2 on 2021-04-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='needy',
            name='request',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='needy',
            name='state_choice',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='Request',
        ),
    ]
