# Generated by Django 3.2 on 2021-04-20 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needy',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='needy',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='resource',
            name='created_at',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='resource',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
