# Generated by Django 3.2 on 2021-04-29 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0002_auto_20210427_0053'),
        ('receiver', '0002_auto_20210429_2036'),
    ]

    operations = [
    ]
