# Generated by Django 3.2 on 2021-04-19 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0002_auto_20210419_0111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='needy',
            old_name='request',
            new_name='req',
        ),
    ]
