# Generated by Django 3.1.7 on 2021-04-19 13:43

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0003_rename_request_needy_req'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(default='', max_length=200)),
                ('state_choice', models.CharField(default='', max_length=200)),
                ('city_choice', models.CharField(default='', max_length=200)),
                ('cname', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('last_updated', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='needy',
            name='city_choice',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='needy',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
