# Generated by Django 3.1.7 on 2021-04-19 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0004_auto_20210419_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resources',
            old_name='city_choice',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='resources',
            old_name='cname',
            new_name='contact_name',
        ),
        migrations.RenameField(
            model_name='resources',
            old_name='email',
            new_name='email_id',
        ),
        migrations.RenameField(
            model_name='resources',
            old_name='rname',
            new_name='resource_name',
        ),
        migrations.RenameField(
            model_name='resources',
            old_name='state_choice',
            new_name='state',
        ),
    ]
