# Generated by Django 3.1.7 on 2021-04-19 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0005_auto_20210419_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='needy',
            old_name='city_choice',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='needy',
            old_name='state_choice',
            new_name='state',
        ),
    ]
