# Generated by Django 3.1.7 on 2021-04-19 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0006_auto_20210419_1920'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resources',
            new_name='Resource',
        ),
    ]
