# Generated by Django 3.2 on 2021-04-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0006_auto_20210423_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='email_id',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='web_site',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
