# Generated by Django 3.1.7 on 2021-04-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0007_auto_20210419_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='needy',
            name='email_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='needy',
            name='phone',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='resource',
            name='email_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='resource',
            name='phone',
            field=models.CharField(default='', max_length=200),
        ),
    ]
