# Generated by Django 3.2 on 2021-04-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0008_auto_20210423_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
